
var app = getApp()

Page({
  data: {
    cars: [
      { "title": "奥迪", "image": "../../images/car/A_奥迪.jpg" },
      { "title": "阿斯顿・马丁", "image": "../../images/car/A_阿斯顿・马丁.jpg" },
      { "title": "阿尔法・罗密欧", "image": "../../images/car/A_阿尔法・罗密欧.jpg" },
      { "title": "AC Schnitzer", "image": "../../images/car/A_AC Schnitzer.jpg" },
      { "title": "ARCFOX", "image": "../../images/car/A_ARCFOX.jpg" },
      { "title": "安凯客车", "image": "../../images/car/A_安凯客车.jpg" },
      { "title": "ALPINA", "image": "../../images/car/A_ALPINA.jpg" },
      { "title": "Apollo", "image": "../../images/car/A_Apollo.jpg" },
      { "title": "Arash", "image": "../../images/car/A_Arash.jpg" },
      { "title": "艾康尼克", "image": "../../images/car/A_艾康尼克.jpg" },
      { "title": "奔驰", "image": "../../images/car/B_奔驰.jpg" },
      { "title": "宝马", "image": "../../images/car/B_宝马.jpg" },
      { "title": "本田", "image": "../../images/car/B_本田.jpg" },
      { "title": "别克", "image": "../../images/car/B_别克.jpg" },
      { "title": "比亚迪", "image": "../../images/car/B_比亚迪.jpg" },
      { "title": "宝骏", "image": "../../images/car/B_宝骏.jpg" },
      { "title": "标致", "image": "../../images/car/B_标致.jpg" },
      { "title": "保时捷", "image": "../../images/car/B_保时捷.jpg" },
      { "title": "北京", "image": "../../images/car/B_北京.jpg" },
      { "title": "宾利", "image": "../../images/car/B_宾利.jpg" },
      { "title": "奔腾", "image": "../../images/car/B_奔腾.jpg" },
      { "title": "北汽幻速", "image": "../../images/car/B_北汽幻速.jpg" },
      { "title": "北汽绅宝", "image": "../../images/car/B_北汽绅宝.jpg" },
      { "title": "宝沃", "image": "../../images/car/B_宝沃.jpg" },
      { "title": "北汽制造", "image": "../../images/car/B_北汽制造.jpg" },
      { "title": "巴博斯", "image": "../../images/car/B_巴博斯.jpg" },
      { "title": "北汽威旺", "image": "../../images/car/B_北汽威旺.jpg" },
      { "title": "北汽新能源", "image": "../../images/car/B_北汽新能源.jpg" },
      { "title": "布加迪", "image": "../../images/car/B_布加迪.jpg" },
      { "title": "比速汽车", "image": "../../images/car/B_比速汽车.jpg" },
      { "title": "北汽道达", "image": "../../images/car/B_北汽道达.jpg" },
      { "title": "长安", "image": "../../images/car/C_长安.jpg" },
      { "title": "长城", "image": "../../images/car/C_长城.jpg" },
      { "title": "长安欧尚", "image": "../../images/car/C_长安欧尚.jpg" },
      { "title": "昌河", "image": "../../images/car/C_昌河.jpg" },
      { "title": "成功汽车", "image": "../../images/car/C_成功汽车.jpg" },
      { "title": "长安轻型车", "image": "../../images/car/C_长安轻型车.jpg" },
      { "title": "长安跨越", "image": "../../images/car/C_长安跨越.jpg" },
      { "title": "Caterham", "image": "../../images/car/C_Caterham.jpg" },
      { "title": "长江EV", "image": "../../images/car/C_长江EV.jpg" },
      { "title": "大众", "image": "../../images/car/D_大众.jpg" },
      { "title": "东风", "image": "../../images/car/D_东风.jpg" },
      { "title": "东风风行", "image": "../../images/car/D_东风风行.jpg" },
      { "title": "东风风神", "image": "../../images/car/D_东风风神.jpg" },
      { "title": "东风风光", "image": "../../images/car/D_东风风光.jpg" },
      { "title": "东风小康", "image": "../../images/car/D_东风小康.jpg" },
      { "title": "道奇", "image": "../../images/car/D_道奇.jpg" },
      { "title": "东南", "image": "../../images/car/D_东南.jpg" },
      { "title": "DS", "image": "../../images/car/D_DS.jpg" },
      { "title": "东风风度", "image": "../../images/car/D_东风风度.jpg" },
      { "title": "电咖", "image": "../../images/car/D_电咖.jpg" },
      { "title": "Dacia", "image": "../../images/car/D_Dacia.jpg" },
      { "title": "DMC", "image": "../../images/car/D_DMC.jpg" },
      { "title": "大发", "image": "../../images/car/D_大发.jpg" },
      { "title": "丰田", "image": "../../images/car/F_丰田.jpg" },
      { "title": "福特", "image": "../../images/car/F_福特.jpg" },
      { "title": "法拉利", "image": "../../images/car/F_法拉利.jpg" },
      { "title": "福田", "image": "../../images/car/F_福田.jpg" },
      { "title": "福迪", "image": "../../images/car/F_福迪.jpg" },
      { "title": "菲亚特", "image": "../../images/car/F_菲亚特.jpg" },
      { "title": "福汽启腾", "image": "../../images/car/F_福汽启腾.jpg" },
      { "title": "福田乘用车", "image": "../../images/car/F_福田乘用车.jpg" },
      { "title": "Faraday Future", "image": "../../images/car/F_Faraday Future.jpg" },
      { "title": "Fisker", "image": "../../images/car/F_Fisker.jpg" },
      { "title": "广汽传祺", "image": "../../images/car/G_广汽传祺.jpg" },
      { "title": "观致", "image": "../../images/car/G_观致.jpg" },
      { "title": "GMC", "image": "../../images/car/G_GMC.jpg" },
      { "title": "广汽吉奥", "image": "../../images/car/G_广汽吉奥.jpg" },
      { "title": "广汽新能源", "image": "../../images/car/G_广汽新能源.jpg" },
      { "title": "国金汽车", "image": "../../images/car/G_国金汽车.jpg" },
      { "title": "GLM", "image": "../../images/car/G_GLM.jpg" },
      { "title": "Gumpert", "image": "../../images/car/G_Gumpert.jpg" },
      { "title": "光冈", "image": "../../images/car/G_光冈.jpg" },
      { "title": "哈弗", "image": "../../images/car/H_哈弗.jpg" },
      { "title": "海马", "image": "../../images/car/H_海马.jpg" },
      { "title": "黄海", "image": "../../images/car/H_黄海.jpg" },
      { "title": "红旗", "image": "../../images/car/H_红旗.jpg" },
      { "title": "华泰", "image": "../../images/car/H_华泰.jpg" },
      { "title": "汉腾汽车", "image": "../../images/car/H_汉腾汽车.jpg" },
      { "title": "海格", "image": "../../images/car/H_海格.jpg" },
      { "title": "哈飞", "image": "../../images/car/H_哈飞.jpg" },
      { "title": "恒天", "image": "../../images/car/H_恒天.jpg" },
      { "title": "华泰新能源", "image": "../../images/car/H_华泰新能源.jpg" },
      { "title": "华凯", "image": "../../images/car/H_华凯.jpg" },
      { "title": "华颂", "image": "../../images/car/H_华颂.jpg" },
      { "title": "华骐", "image": "../../images/car/H_华骐.jpg" },
      { "title": "Hennessey", "image": "../../images/car/H_Hennessey.jpg" },
      { "title": "悍马", "image": "../../images/car/H_悍马.jpg" },
      { "title": "合众", "image": "../../images/car/H_合众.jpg" },
      { "title": "华利", "image": "../../images/car/H_华利.jpg" },
      { "title": "华普", "image": "../../images/car/H_华普.jpg" },
      { "title": "霍顿", "image": "../../images/car/H_霍顿.jpg" },
      { "title": "Icona", "image": "../../images/car/I_Icona.jpg" },
      { "title": "吉利汽车", "image": "../../images/car/J_吉利汽车.jpg" },
      { "title": "Jeep", "image": "../../images/car/J_Jeep.jpg" },
      { "title": "江淮", "image": "../../images/car/J_江淮.jpg" },
      { "title": "捷豹", "image": "../../images/car/J_捷豹.jpg" },
      { "title": "金杯", "image": "../../images/car/J_金杯.jpg" },
      { "title": "江铃", "image": "../../images/car/J_江铃.jpg" },
      { "title": "金龙", "image": "../../images/car/J_金龙.jpg" },
      { "title": "九龙", "image": "../../images/car/J_九龙.jpg" },
      { "title": "江铃集团轻汽", "image": "../../images/car/J_江铃集团轻汽.jpg" },
      { "title": "江铃集团新能源", "image": "../../images/car/J_江铃集团新能源.jpg" },
      { "title": "金旅", "image": "../../images/car/J_金旅.jpg" },
      { "title": "君马汽车", "image": "../../images/car/J_君马汽车.jpg" },
      { "title": "凯迪拉克", "image": "../../images/car/K_凯迪拉克.jpg" },
      { "title": "开瑞", "image": "../../images/car/K_开瑞.jpg" },
      { "title": "凯翼", "image": "../../images/car/K_凯翼.jpg" },
      { "title": "KTM", "image": "../../images/car/K_KTM.jpg" },
      { "title": "卡威", "image": "../../images/car/K_卡威.jpg" },
      { "title": "克莱斯勒", "image": "../../images/car/K_克莱斯勒.jpg" },
      { "title": "科尼赛克", "image": "../../images/car/K_科尼赛克.jpg" },
      { "title": "卡尔森", "image": "../../images/car/K_卡尔森.jpg" },
      { "title": "凯佰赫", "image": "../../images/car/K_凯佰赫.jpg" },
      { "title": "雷克萨斯", "image": "../../images/car/L_雷克萨斯.jpg" },
      { "title": "路虎", "image": "../../images/car/L_路虎.jpg" },
      { "title": "铃木", "image": "../../images/car/L_铃木.jpg" },
      { "title": "林肯", "image": "../../images/car/L_林肯.jpg" },
      { "title": "雷诺", "image": "../../images/car/L_雷诺.jpg" },
      { "title": "猎豹汽车", "image": "../../images/car/L_猎豹汽车.jpg" },
      { "title": "陆风", "image": "../../images/car/L_陆风.jpg" },
      { "title": "领克", "image": "../../images/car/L_领克.jpg" },
      { "title": "兰博基尼", "image": "../../images/car/L_兰博基尼.jpg" },
      { "title": "劳斯莱斯", "image": "../../images/car/L_劳斯莱斯.jpg" },
      { "title": "力帆汽车", "image": "../../images/car/L_力帆汽车.jpg" },
      { "title": "理念", "image": "../../images/car/L_理念.jpg" },
      { "title": "路特斯", "image": "../../images/car/L_路特斯.jpg" },
      { "title": "莲花汽车", "image": "../../images/car/L_莲花汽车.jpg" },
      { "title": "LeSEE", "image": "../../images/car/L_LeSEE.jpg" },
      { "title": "蓝旗亚", "image": "../../images/car/L_蓝旗亚.jpg" },
      { "title": "朗世", "image": "../../images/car/L_朗世.jpg" },
      { "title": "领志", "image": "../../images/car/L_领志.jpg" },
      { "title": "马自达", "image": "../../images/car/M_马自达.jpg" },
      { "title": "名爵", "image": "../../images/car/M_名爵.jpg" },
      { "title": "玛莎拉蒂", "image": "../../images/car/M_玛莎拉蒂.jpg" },
      { "title": "MINI", "image": "../../images/car/M_MINI.jpg" },
      { "title": "迈凯伦", "image": "../../images/car/M_迈凯伦.jpg" },
      { "title": "摩根", "image": "../../images/car/M_摩根.jpg" },
      { "title": "迈巴赫", "image": "../../images/car/M_迈巴赫.jpg" },
      { "title": "纳智捷", "image": "../../images/car/N_纳智捷.jpg" },
      { "title": "南京金龙", "image": "../../images/car/N_南京金龙.jpg" },
      { "title": "nanoFLOWCELL", "image": "../../images/car/N_nanoFLOWCELL.jpg" },
      { "title": "NEVS", "image": "../../images/car/N_NEVS.jpg" },
      { "title": "Noble", "image": "../../images/car/N_Noble.jpg" },
      { "title": "讴歌", "image": "../../images/car/O_讴歌.jpg" },
      { "title": "欧朗", "image": "../../images/car/O_欧朗.jpg" },
      { "title": "欧宝", "image": "../../images/car/O_欧宝.jpg" },
      { "title": "帕加尼", "image": "../../images/car/P_帕加尼.jpg" },
      { "title": "Polestar", "image": "../../images/car/P_Polestar.jpg" },
      { "title": "佩奇奥", "image": "../../images/car/P_佩奇奥.jpg" },
      { "title": "起亚", "image": "../../images/car/Q_起亚.jpg" },
      { "title": "奇瑞", "image": "../../images/car/Q_奇瑞.jpg" },
      { "title": "启辰", "image": "../../images/car/Q_启辰.jpg" },
      { "title": "庆铃汽车", "image": "../../images/car/Q_庆铃汽车.jpg" },
      { "title": "祺智", "image": "../../images/car/Q_祺智.jpg" },
      { "title": "奇点汽车", "image": "../../images/car/Q_奇点汽车.jpg" },
      { "title": "前途", "image": "../../images/car/Q_前途.jpg" },
      { "title": "日产", "image": "../../images/car/R_日产.jpg" },
      { "title": "荣威", "image": "../../images/car/R_荣威.jpg" },
      { "title": "如虎", "image": "../../images/car/R_如虎.jpg" },
      { "title": "Rezvani", "image": "../../images/car/R_Rezvani.jpg" },
      { "title": "Rimac", "image": "../../images/car/R_Rimac.jpg" },
      { "title": "Rinspeed", "image": "../../images/car/R_Rinspeed.jpg" },
      { "title": "瑞麒", "image": "../../images/car/R_瑞麒.jpg" },
      { "title": "斯柯达", "image": "../../images/car/S_斯柯达.jpg" },
      { "title": "三菱", "image": "../../images/car/S_三菱.jpg" },
      { "title": "斯巴鲁", "image": "../../images/car/S_斯巴鲁.jpg" },
      { "title": "上汽大通", "image": "../../images/car/S_上汽大通.jpg" },
      { "title": "双龙", "image": "../../images/car/S_双龙.jpg" },
      { "title": "smart", "image": "../../images/car/S_smart.jpg" },
      { "title": "思铭", "image": "../../images/car/S_思铭.jpg" },
      { "title": "SWM斯威汽车", "image": "../../images/car/S_SWM斯威汽车.jpg" },
      { "title": "赛麟", "image": "../../images/car/S_赛麟.jpg" },
      { "title": "Scion", "image": "../../images/car/S_Scion.jpg" },
      { "title": "SPIRRA", "image": "../../images/car/S_SPIRRA.jpg" },
      { "title": "SSC", "image": "../../images/car/S_SSC.jpg" },
      { "title": "萨博", "image": "../../images/car/S_萨博.jpg" },
      { "title": "上海", "image": "../../images/car/S_上海.jpg" },
      { "title": "世爵", "image": "../../images/car/S_世爵.jpg" },
      { "title": "双环", "image": "../../images/car/S_双环.jpg" },
      { "title": "特斯拉", "image": "../../images/car/T_特斯拉.jpg" },
      { "title": "腾势", "image": "../../images/car/T_腾势.jpg" },
      { "title": "泰克鲁斯・腾风", "image": "../../images/car/T_泰克鲁斯・腾风.jpg" },
      { "title": "VLF Automotive", "image": "../../images/car/V_VLF Automotive.jpg" },
      { "title": "沃尔沃", "image": "../../images/car/W_沃尔沃.jpg" },
      { "title": "五菱汽车", "image": "../../images/car/W_五菱汽车.jpg" },
      { "title": "WEY", "image": "../../images/car/W_WEY.jpg" },
      { "title": "五十铃", "image": "../../images/car/W_五十铃.jpg" },
      { "title": "蔚来", "image": "../../images/car/W_蔚来.jpg" },
      { "title": "潍柴英致", "image": "../../images/car/W_潍柴英致.jpg" },
      { "title": "W Motors", "image": "../../images/car/W_W Motors.jpg" },
      { "title": "威麟", "image": "../../images/car/W_威麟.jpg" },
      { "title": "威马汽车", "image": "../../images/car/W_威马汽车.jpg" },
      { "title": "威兹曼", "image": "../../images/car/W_威兹曼.jpg" },
      { "title": "沃克斯豪尔", "image": "../../images/car/W_沃克斯豪尔.jpg" },
      { "title": "现代", "image": "../../images/car/X_现代.jpg" },
      { "title": "雪佛兰", "image": "../../images/car/X_雪佛兰.jpg" },
      { "title": "雪铁龙", "image": "../../images/car/X_雪铁龙.jpg" },
      { "title": "西雅特", "image": "../../images/car/X_西雅特.jpg" },
      { "title": "小鹏汽车", "image": "../../images/car/X_小鹏汽车.jpg" },
      { "title": "英菲尼迪", "image": "../../images/car/Y_英菲尼迪.jpg" },
      { "title": "一汽", "image": "../../images/car/Y_一汽.jpg" },
      { "title": "依维柯", "image": "../../images/car/Y_依维柯.jpg" },
      { "title": "野马汽车", "image": "../../images/car/Y_野马汽车.jpg" },
      { "title": "驭胜", "image": "../../images/car/Y_驭胜.jpg" },
      { "title": "云度", "image": "../../images/car/Y_云度.jpg" },
      { "title": "永源", "image": "../../images/car/Y_永源.jpg" },
      { "title": "裕路", "image": "../../images/car/Y_裕路.jpg" },
      { "title": "游侠", "image": "../../images/car/Y_游侠.jpg" },
      { "title": "众泰", "image": "../../images/car/Z_众泰.jpg" },
      { "title": "中华", "image": "../../images/car/Z_中华.jpg" },
      { "title": "中兴", "image": "../../images/car/Z_中兴.jpg" },
      { "title": "知豆", "image": "../../images/car/Z_知豆.jpg" },
      { "title": "之诺", "image": "../../images/car/Z_之诺.jpg" },
      { "title": "Zenvo", "image": "../../images/car/Z_Zenvo.jpg" },
      { "title": "正道汽车", "image": "../../images/car/Z_正道汽车.jpg" }
    ],
    step: 1
  },
  onLoad: function () {
    var that = this
    //调用应用实例的方法获取全局数据
    app.getUserInfo(function (userInfo) {
      console.log(userInfo)
      that.setData({
        userInfo: userInfo
      })
    })

  },

  updateStep: function (event) {
    console.log(event.currentTarget.dataset.step)
    this.setData({
      step: parseInt(event.currentTarget.dataset.step)
    })
  },

  onShareAppMessage: function (res) {
    if (res.from === 'button') {
      // 来自页面内转发按钮
      console.log(res.target)
    }
    return {
      title: '车牌大全',
      path: '/pages/car/car',
      success: function (res) {
        console.log(res)
      },
      fail: function (res) {
        console.log(res)
      }
    }
  }

});

